<a href="https://colab.research.google.com/github/devp712/Micro-Credentials-Winter-2022/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [3]:
# importing the NumPy library and defining it as np
import numpy as np

#### Create an array of 20 zeros 

In [6]:
# Using the zeros function to create a numpy array of a list of 20 0s
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [7]:
# Using the ones function to create a numpy array of a list of 10 1s
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
# using the ones function to get an array of 10 1s then multiplying each value in the array by 5 to get an array of 10 5s
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [11]:
# Using the arange function with parameters 10,51 in order to create an array that spans from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
# Using the arange function with parameters 10,51,2 to create an array than spans from 10 to 50 and increments by 2
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
# first created an array of values from 0 to 8 and then used the reshape function in order to create a matrix with 3 row and 3 columns
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [16]:
# using the eye function to create a 3x3 matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
# using the random.rand function to generate a random number between 0 and 1 across a uniform distribution
np.random.rand(1)

array([0.1342098])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
# using the random.randn function to generate random numbers from a standard normal distribution 
np.random.randn(25)

array([-0.5741811 ,  0.63615699, -1.13655622, -1.00839475,  0.12426082,
        0.38666086, -0.65489124,  0.36390852, -0.02775257, -0.22296663,
       -0.92599205,  0.19077471, -0.13801618, -0.43061141,  0.82286198,
        1.00430745,  0.56351726,  0.64898757,  2.20001959, -1.14170914,
        0.25998721, -0.69192452, -0.32934049, -0.9359182 , -0.10589249])

#### Create the following matrix:

In [26]:
# using the arange function to generate an array of numbers from .01 to 1 with an increment of .01 and then reshaping the array to conatin 10 lists with 10 values
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [24]:
# using the linespace function to enerate evenly 20 space numbers in the range 0 to 1 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [46]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [67]:
# creating a replica of the mat variable
new_mat = np.arange(1,26).reshape(5,5)
# indexing the new_mat variable to select all lists greater than and equal to the 3rd list and all values greater than and equal to the 2nd value in a list
new_mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [71]:
# indexing the new_mat variable to select the 3rd list and the 4th value in that list
new_mat[3,4:]

array([20])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [72]:
# Indexing new_mat to select all lists up to the 3rd list and all values between the second and third value
new_mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [62]:
# indexing new_mat to select the 4th list in the variable
new_mat[4:24]

array([[21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [64]:
# Indexing new_mat to select all lists greater than and eaul to the 3rd list and all values up to the 24th value
new_mat[3:24]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [47]:
# using the np.sum function to get a sum of all the values in mat
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [48]:
# using the np.std function to get the standard deviation of the values in mat
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [49]:
# using the sum function and setting the axis equal to 0 so columns are selected and summed
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Cheers!